### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by ngu-khoi** [rau/content#135]
- [ ] Find tshirt provider and minimalist cool design
- [ ] Prep party
- [ ] Get some dates on BU semester start
- [ ] Offer money to club leaders for each signup through unique referral link

**Comment by rau** [comment]
Possible partnership incentives for the funniest people (mcdonalds burgers), rewards

Top 10 users on leaderboard all receive shoes, clothes, branded with Pong
