### ISSUE TITLE
Sunday Launch Checklist

### ISSUE THREAD

**Issue by rau** [rau/content#262]
- [x] Fix spacers on feed
- [ ] True up poll design - Raunak
- [x] Make poll extend all the way to the side
- [x] Save bookmark next to share
- [x] Connect messages to backend - Artemas
- [x] Connect notifications to backend - Artemas
- [ ] Connect enable notifications button - Artemas
- [x] Leaderboard 10 second live refresh, only do on page
- [x] Disappear status bar on login screen
- [x] True up onboarding screen - Raunak
- [x] Onboarding screen only once, track on backend
- [x] True up profile design - Khoi
- [x] Add post view navigation from post on profile
- [x] True up new post button from new post view - Raunak
- [x] True up new poll object to be consistent with poll display on feed - Khoi
- [x] Add X button to new post
- [x] Change character limit to 280
- [x] True up settings, place in a caption at bottom technical info
- [x] Create a default privacy policy - Raunak
- [x] Create a default TOS - Raunak
- [x] Create a share app in settings
- [x] Add a referral counter
- [x] Referral Scheme 3$ in settings
- [x] Disabled button based of off whether we turn it on or not on the backend - Raunak - NOT MVP
- [x] Contact us in settings
- [x] Unblock all to delete all blocked posts - Raunak
- [x] Add Joined date for users at bottom
- [x] Community rank on leaderboard once a day - Raunak - NOT MVP
- [x] Fiverr logo TODAY
- [x] Range selector on top true up
- [x] Disappearing navigation bar on bottom when scrolling down feed - Khoi
- [x] Error for we don't support your school yet 
- [x] poll options must be 1 character long at least
- [x] Skip voting
- [x] put sign in config in an environment variable
- [x] images (new and showing) - Raunak

**Comment by rau** [comment]
Finished leaderboard

Starting contact us in settings

**Comment by rau** [comment]
Settings complete fix
Referral scheme frontend and backend
Add joined date at bottom
Onboarding screen only once, track on backend

**Comment by ngu-khoi** [comment]
finish datamanager
do bookmark
disappear status bar
change character limit

**Comment by rau** [comment]
Khoi

Functionality for top filters
pagination for everything in profile
1 character minimum for poll options
Skip voting for poll options, small caption
If post deleted, remove navigation link for comment in. comments on profile

**Comment by rau** [comment]
Raunak

Referral finish frontend and backend
Unblock all frontend and backend

**Comment by rau** [comment]
1) Upon loading of app, check if isSignedIn AND onboarded (DAKeychain for both) is true or not. isSignedIn is determined by the presence of a token and userID. Onboarded is returned as a field upon user login. Onboarded should be set only once (on the BACKEND), after the referralCodeView is completed. This means that if a user does not complete the referral flow by either clicking X or clicking they were referred by someone, it will redisplay the welcome view AND the referral view, but this is intended behavior. We want people to get past the referral view, and only THEN consider them as onboarded.

2) If isSignedIn is not true, redirect to onboarding view, and begin at EmailVerificationView

3) EmailVerificationView will retrigger loadCurrentState, causing isSignedIn to become true. 

4) At that point, check in onboarded in AUTHMANAGER is true. If it is, skip onboarding view and go directly to main interface. 

5) If onboarding in AUTHMANAGER is not true, then start the onboardingview process.

**Comment by rau** [comment]
skipkhoicunt
