### ISSUE TITLE
[FEATURE] Prod Launch Checklist

### ISSUE THREAD

**Issue by rau** [rau/content#288]
## Acceptance criteria

- [x] Update logo assets
- [x] Make entire profile page background primary color (IF IOS 15/16)
- [x] Last post doesn't show up with white background 
- [x] Change incentives on profile page to something funny
- [x] Make random prompt on new post not flashing change if closing out or posting something
- [x] Polls need to be proportioned
- [x] Share button needs to create an image
- [x] Add lesley colors 
- [x] Your referral code title on referrals page
- [x] Change referral block to user with most referrals wins a gift card each ewek
- [x] Unblock functionality
- [x] usepong.com on webflow, update privacy policy links and tos link
- [x] change views to post karma and comment karma, random sf icon
- [x] Fix nicknames
- [x] Fix admin feed view
- [x] Remove DMS from admin feed view
- [x] Blocking user should delete conversation
- [x] Get rid of me and anon
- [x] Enable notifications button only show if user doesn't have notifications on
- [x] Make conversations bolded if unread, otherwise not bolded
- [x] If title empty: remove colon, add exclamation mark for notification
- [x] If title empty in messages, "Untitled post"
- [x] Change voting backend to just accept
- [x] Get rid of keyboard down button
- [x] Add save nickname confirmation toast
- [x] Force update app if update available
- [x] Error handling for referrals

**Comment by ngu-khoi** [comment]
https://stackoverflow.com/questions/59946147/swiftui-cancel-tapgesture-on-parent-view

onTap to dismiss is buggy since it trigger on tap of a button that tries to show
