### ISSUE TITLE
[FEATURE] New build checklist

### ISSUE THREAD

**Issue by rau** [rau/content#289]
## Acceptance criteria

- [x] push microsoft and google login to bottom of screen, add microsoft logo
- [x] remove marketplace, put notifications back
- [x] push to app store connect
