### ISSUE TITLE
[FEATURE] checklist

### ISSUE THREAD

**Issue by rau** [rau/content#407]
## Acceptance criteria

- [x] buttons pop on tabbar when clicked
- [x] 'BU' pops when clicked
- [x] Messages icon too bolded
- [x] Non selected tab (top hot new), all should be bold
- [x] if no notifications, don't show 'Mark all read' button
- [x] capitalize 'All' in mark all read
- [x] copy notifications figma
- [x] bold posts comments about on profile
- [x] posts comments about padding from profile header
- [x] comment SF icon needs to be fixed in postbubble, also needs to be same size as save and share icon
- [x] animate bookmark fill and unfill
- [x] upvote and downvote arrows bigger
- [x] trash can SF icon
- [x] capitalize all 'You have no...'
- [x] copy messaging figma
- [x] clicking plus button for new post makes button transparent for a second
- [x] clicking image library on new post disappears image and poll buttons
- [x] replace tap to try again loading indicator at bottom of feed with just a progressview
- [x] referrals figma
- [x] make progress bar on referrals page work
- [x] images are low quality
